version: '3.8'

services:
  streaming-p2p:
    build: .
    ports:
      - "8080:8080"
    #carpeta de videos
    volumes:
      - ./src/main/resources/videos:/app/src/main/resources/videos

    #se reinicia si algo falla
    restart: always